project:
  type: website
  output-dir: docs

website:
  title: "Andrey Pafnutyev"
  navbar:
    left:
      - text: "About Me"
        href: aboutme.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Resume"
        href: resume.qmd
      - text: "Contact"
        href: contact.qmd
    right: 
      - icon: github
        href: https://github.com/616797
      - icon: linkedin
        href: https://www.linkedin.com/in/andrey-pafnutyev/


format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" />



