---
title: "About Me"
---

## Professional Introduction

I have experience with CRM systems and user training. I can structure data, prepare documentation and analytics to help optimize processes. I am constantly striving to evolve, learn new methods and technologies for working with data, which allows me to adapt to new tasks and quickly master new tools. 

## Interests

Over the past three years of professional working experience, I learned and mastered my information technology and research skills, focusing on data collection and aggregation in healthcare-related fields. This hands-on experience has been challenging and rewarding, pushing me to innovate and excel in IT, marketing analysis, tax reporting and healthcare data management. Leading and improving Affordable Care Act delivery, and compliance packages through efficient utilization of updated data management tools, as a top 5% implementation and data manager at the certified member of Women's Business Enterprise National Council (WBENC) & a leading specialist in ACA reporting and compliance company, BenefitScape, I developed passion for healthcare equality and access data analytics projects.

## Career Goals

I seek to work in an environment that values cutting-edge technology, teamwork and CRM system development. I am ready not only to apply my experience in CRM development, user training and data analysis, but also to continue learning, developing and mastering new tools to contribute to the company's digital transformation. It is important for me to assist the team in achieving common goals by sharing knowledge and supporting each other. 
